version: '3.5'
services:
  mavenwebapplok:
      image: lokeshsdockerhub/mavenwebapplok:VERSION
      ports: 
       - 9182:8080
      networks:
       - mavenwebapplokbridge
      volumes:
       - mavenwebappvol:/usr/local/tomcat/
networks:
  mavenwebapplokbridge:
     driver: bridge
volumes:
  mavenwebappvol:
     external: true     

    
